# Generated by Django 5.2.17 on 2026-08-14 03:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_chatmessage_parent_confidence_and_more'),
        ('topics', '0002_remove_knowledgenode_origin_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance_rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='ユーザーの自己申告(理解できたか)から算出した0〜5の記憶定着度評価')),
                ('response_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='chat.attempt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('easiness_factor', models.FloatField(default=2.5, help_text='難易度係数(最小値1.3を目安にアプリ側でバリデーション)')),
                ('interval_days', models.IntegerField(default=0, help_text='次回復習までの日数間隔')),
                ('repetitions', models.IntegerField(default=0, help_text='連続で完了できた回数')),
                ('next_review_at', models.DateTimeField(default=django.utils.timezone.now, help_text='復習問題を出題する予定日時')),
                ('last_learned_at', models.DateTimeField(blank=True, help_text='最後に学習(挑戦・復習)した日時', null=True)),
                ('learned_count', models.PositiveIntegerField(default=0, help_text='学習した回数の累計。SM-2の repetitions と違い、失敗しても0にリセットしない')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedule', to='topics.knowledgenode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
