# Generated by Django 5.2.17 on 2026-08-14 04:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        ("topics", "0002_remove_knowledgenode_origin_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="parent_confidence",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("low", "Low")],
                help_text="JA: 親ノード推定の確信度 / VI: Độ tin cậy của việc đoán node cha",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="parent_confirmed",
            field=models.BooleanField(
                default=True,
                help_text="JA: True=親ノードが確定済み(ユーザー明示指定 or 確認済み)。False=AI推定のみで未確認、フロントで確認UIを出す必要あり。 VI: True=node cha đã chốt (user tự chọn hoặc đã confirm). False=mới chỉ là AI đoán, chưa confirm, frontend cần hiển thị UI xác nhận.",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="suggested_parent",
            field=models.ForeignKey(
                blank=True,
                help_text="JA: AIが推定した親ノード / VI: Node cha do AI đề xuất",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="knowledge_node",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_session",
                to="topics.knowledgenode",
            ),
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hint_count",
                    models.PositiveIntegerField(default=0, help_text="ヒントを求めた回数"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="完了した日時", null=True),
                ),
                (
                    "chat_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
