# Generated by Django 5.2.17 on 2026-08-15 18:46

from django.db import migrations, models


def mark_existing_user_messages_as_trunk(apps, schema_editor):
    """
    JA: 既存のユーザー発言を幹(TRUNK)として扱う。step_kind の既定は NONE なので、
        このデータ移行が無いと既存セッションの思考ツリーが全て空になってしまう。
        既存分は幹/枝を判定する材料が無いため、一律で幹とみなす(木が線形になるだけ)。
    VI: Coi các phát ngôn user đã có là thân (TRUNK). Mặc định của step_kind là NONE nên
        nếu thiếu bước chuyển dữ liệu này, cây tư duy của các session cũ sẽ rỗng hết.
        Dữ liệu cũ không còn căn cứ để phân thân/nhánh nên coi tất cả là thân (cây chỉ thành đường thẳng).
    """
    ChatMessage = apps.get_model("chat", "ChatMessage")
    ChatMessage.objects.filter(sender="USER").update(step_kind="TRUNK")


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_merge_20260814_1404"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="step_kind",
            field=models.CharField(
                choices=[
                    ("NONE", "ステップにしない / Không phải bước"),
                    ("TRUNK", "幹(大きなステップ) / Thân (bước lớn)"),
                    ("BRANCH", "枝(派生した質問) / Nhánh (câu hỏi phái sinh)"),
                ],
                default="NONE",
                help_text="JA: 幹/枝/ステップ外の区別 / VI: Phân biệt thân / nhánh / không phải bước",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="step_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="JA: ノードに表示する要約タイトル / VI: Tiêu đề tóm tắt hiển thị trên node",
                max_length=120,
            ),
        ),
        migrations.RunPython(
            mark_existing_user_messages_as_trunk,
            migrations.RunPython.noop,
        ),
    ]
