# Generated by Django 5.2.17 on 2026-08-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_chatmessage_step_kind_chatmessage_step_title"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completed_at__isnull", True)),
                fields=("chat_session",),
                name="unique_active_attempt_per_session",
            ),
        ),
    ]
