# Generated by Django 5.2.17 on 2026-08-14 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgenode",
            name="origin_node",
        ),
    ]
